[package]
name = "longboy"
description = "longboy networking protocol"
version = "1.0.0"
license = "BSD-3-Clause"
repository = "https://github.com/JKurzer/longboy"
edition = "2021"
autotests = false

[[test]]
name = "tests"
path = "tests/lib.rs"

[dependencies]
anyhow = "1.0.93"
cipher = "=0.5.0-pre.7"
derive_builder = { version = "0.20.2", features = ["clippy"] }
enum-map = "2.7.3"
flume = "0.11.1"
fnv = "1.0.7"
generic-array = "1.1.0"
quinn = "0.11.6"
rc5 = { git = "https://github.com/RustCrypto/block-ciphers.git", rev = "4da9b802de52a3326fdc74d559caddd57042fed2" }
thunderdome = "0.6.1"
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = "0.7.12"
typenum = { version = "1.17.0", features = ["const-generics"] }
zerocopy = { version = "0.8.10", features = ["derive"] }

[dev-dependencies]
parking_lot = "0.12.3"
rcgen = "0.13.1"

[features]
